=== bL0p/dataRepository/build/DataModelSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/DataModelSchema" 
	xmlns:dm="http://www.example.org/DataModelSchema" 
	elementFormDefault="qualified">

<xs:element name="DataModel">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="SpecificationInfo" type="dm:specificationInfo" />
			<xs:element minOccurs="0" maxOccurs="1" name="mappings" type="dm:mappings" />
			<xs:element minOccurs="1" maxOccurs="unbounded" name="Entity" type="dm:entity" />
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Relation" type="dm:relation" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:complexType name="specificationInfo">
	<xs:sequence>
		<xs:element minOccurs="1" maxOccurs="1" name="dataModelURI" type="xs:string" />
		<xs:element minOccurs="1" maxOccurs="1" name="activityModelURI" type="xs:string" />
		<xs:element minOccurs="1" maxOccurs="1" name="goalModelURI" type="xs:string" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="entity">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="id" type="xs:string" />
			<xs:element minOccurs="1" maxOccurs="1" name="Name" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Attribute" type="dm:attribute" />
		</xs:sequence>
</xs:complexType>

<xs:complexType name="attribute">
	<xs:sequence>
		<xs:element minOccurs="1" maxOccurs="1" name="Name" type="xs:string" />
		<xs:element minOccurs="1" maxOccurs="1" name="Type" type="dm:attType" />
		<xs:element minOccurs="1" maxOccurs="1" name="isKey" type="xs:boolean" />
	</xs:sequence>
</xs:complexType>

<xs:simpleType name="attType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="STRING" />
		<xs:enumeration value="BOOLEAN" />
		<xs:enumeration value="NUMBER" />
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="relation">
	<xs:sequence>
		<xs:element minOccurs="1" maxOccurs="1" name="EntityOne" type="dm:entityRelation" />
		<xs:element minOccurs="1" maxOccurs="1" name="EntityTwo" type="dm:entityRelation" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="entityRelation">
	<xs:sequence>
		<xs:element minOccurs="1" maxOccurs="1" name="EntityID" type="xs:string" />
		<xs:element minOccurs="1" maxOccurs="1" name="EntityCardinality" type="dm:cardinality" />
		<xs:element minOccurs="1" maxOccurs="1" name="isEntityKey" type="xs:boolean" />
	</xs:sequence>
</xs:complexType>

<xs:simpleType name="cardinality">
	<xs:restriction base="xs:string">
		<xs:enumeration value="MANY" />
		<xs:enumeration value="ZERO_OR_ONE" />
		<xs:enumeration value="ONE" />
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="mappings">
	<xs:sequence>
		<xs:element minOccurs="1" maxOccurs="unbounded" name="mapping" type="dm:mapping" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="mapping">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="varName" type="xs:string" />
			<xs:element minOccurs="1" maxOccurs="unbounded" name="mapsTo" type="xs:string"/>
		</xs:sequence>
</xs:complexType>

</xs:schema>

=== bL0p/dataRepository/build/MedicalEpisodeDataModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<dm:DataModel xmlns:dm="http://www.example.org/DataModelSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/DataModelSchema DataModelSchema.xsd ">
  <dm:SpecificationInfo>
    <dm:dataModelURI>MedicalEpisodeDataModel</dm:dataModelURI>
    <dm:activityModelURI>MedicalEpisode</dm:activityModelURI>
    <dm:goalModelURI>Medical_Episode_GSpec_0</dm:goalModelURI>
  </dm:SpecificationInfo>
  <dm:mappings>
  	<dm:mapping>
  		<dm:varName>Patient</dm:varName>
  		<dm:mapsTo>Patient</dm:mapsTo>
  	</dm:mapping>
  	<dm:mapping>
  		<dm:varName>AdminPatientData</dm:varName>
  		<dm:mapsTo>Patient Data.Height</dm:mapsTo>
  		<dm:mapsTo>Patient Data.Weight</dm:mapsTo>
  	</dm:mapping>
  	<dm:mapping>
  		<dm:varName>NursePatientData</dm:varName>
  		<dm:mapsTo>Patient Data.Physical Report</dm:mapsTo>
  		<dm:mapsTo>Patient Data.Physical Examination</dm:mapsTo>
  	</dm:mapping>
  	<dm:mapping>
  		<dm:varName>Prescription</dm:varName>
  		<dm:mapsTo>Prescription</dm:mapsTo>
  	</dm:mapping>
  	<dm:mapping>
  		<dm:varName>MedicalReport</dm:varName>
  		<dm:mapsTo>Medical Report</dm:mapsTo>
  	</dm:mapping>
  	<dm:mapping>
  		<dm:varName>EpisodeClosed</dm:varName>
  		<dm:mapsTo>Episode.Closed</dm:mapsTo>
  	</dm:mapping>
  	<dm:mapping>
  		<dm:varName>PatientName</dm:varName>
  		<dm:mapsTo>Patient.Name</dm:mapsTo>
  	</dm:mapping>
  </dm:mappings>
  <dm:Entity>
    <dm:id>Patient_0</dm:id>
    <dm:Name>Patient</dm:Name>
    <dm:Attribute>
    	<dm:Name>Name</dm:Name>
    	<dm:Type>STRING</dm:Type>
    	<dm:isKey>true</dm:isKey>
    </dm:Attribute>
    <dm:Attribute>
    	<dm:Name>Address</dm:Name>
    	<dm:Type>STRING</dm:Type>
    	<dm:isKey>false</dm:isKey>
    </dm:Attribute>
    <dm:Attribute>
    	<dm:Name>PhoneNumber</dm:Name>
    	<dm:Type>STRING</dm:Type>
    	<dm:isKey>false</dm:isKey>
    </dm:Attribute>
    <dm:Attribute>
    	<dm:Name>Gender</dm:Name>
    	<dm:Type>STRING</dm:Type>
    	<dm:isKey>false</dm:isKey>
    </dm:Attribute>
  </dm:Entity>
  <dm:Entity>
  	<dm:id>Episode_1</dm:id>
  	<dm:Name>Episode</dm:Name>
  	<dm:Attribute>
  		<dm:Name>Closed</dm:Name>
  		<dm:Type>BOOLEAN</dm:Type>
  		<dm:isKey>false</dm:isKey>
  	</dm:Attribute>
  </dm:Entity>
  <dm:Entity>
  	<dm:id>Patient_Data_2</dm:id>
  	<dm:Name>Patient Data</dm:Name>
  	<dm:Attribute>
  		<dm:Name>Height</dm:Name>
  		<dm:Type>NUMBER</dm:Type>
  		<dm:isKey>false</dm:isKey>
  	</dm:Attribute>
  	<dm:Attribute>
  		<dm:Name>Weight</dm:Name>
  		<dm:Type>NUMBER</dm:Type>
  		<dm:isKey>false</dm:isKey>
  	</dm:Attribute>
  	<dm:Attribute>
  		<dm:Name>Physical Report</dm:Name>
  		<dm:Type>STRING</dm:Type>
  		<dm:isKey>false</dm:isKey>
  	</dm:Attribute>
  	<dm:Attribute>
  		<dm:Name>Physical Examination</dm:Name>
  		<dm:Type>STRING</dm:Type>
  		<dm:isKey>false</dm:isKey>
  	</dm:Attribute>
  	<dm:Attribute>
  		<dm:Name>Medical Examination</dm:Name>
  		<dm:Type>STRING</dm:Type>
  		<dm:isKey>true</dm:isKey>
  	</dm:Attribute>
  </dm:Entity>
  <dm:Entity>
  	<dm:id>Prescription_3</dm:id>
  	<dm:Name>Prescription</dm:Name>
  	<dm:Attribute>
  		<dm:Name>Recipe</dm:Name>
  		<dm:Type>STRING</dm:Type>
  		<dm:isKey>true</dm:isKey>
  	</dm:Attribute>
  </dm:Entity>
  <dm:Entity>
  	<dm:id>Medical_Report_4</dm:id>
  	<dm:Name>Medical Report</dm:Name>
  	<dm:Attribute>
  		<dm:Name>Report</dm:Name>
  		<dm:Type>STRING</dm:Type>
  		<dm:isKey>true</dm:isKey>
  	</dm:Attribute>
  	<dm:Attribute>
  		<dm:Name>Closed</dm:Name>
  		<dm:Type>BOOLEAN</dm:Type>
  		<dm:isKey>false</dm:isKey>
  	</dm:Attribute>
  </dm:Entity>
  <dm:Relation>
  	<dm:EntityOne>
  		<dm:EntityID>Patient_0</dm:EntityID>
  		<dm:EntityCardinality>ONE</dm:EntityCardinality>
  		<dm:isEntityKey>true</dm:isEntityKey>
  	</dm:EntityOne>
  	<dm:EntityTwo>
  		<dm:EntityID>Episode_1</dm:EntityID>
  		<dm:EntityCardinality>ONE</dm:EntityCardinality>
  		<dm:isEntityKey>false</dm:isEntityKey>
  	</dm:EntityTwo>
  </dm:Relation>
  <dm:Relation>
  	<dm:EntityOne>
  		<dm:EntityID>Episode_1</dm:EntityID>
  		<dm:EntityCardinality>ONE</dm:EntityCardinality>
  		<dm:isEntityKey>false</dm:isEntityKey>
  	</dm:EntityOne>
  	<dm:EntityTwo>
  		<dm:EntityID>Patient_Data_2</dm:EntityID>
  		<dm:EntityCardinality>ZERO_OR_ONE</dm:EntityCardinality>
  		<dm:isEntityKey>false</dm:isEntityKey>
  	</dm:EntityTwo>
  </dm:Relation>
  <dm:Relation>
  	<dm:EntityOne>
  		<dm:EntityID>Episode_1</dm:EntityID>
  		<dm:EntityCardinality>ONE</dm:EntityCardinality>
  		<dm:isEntityKey>false</dm:isEntityKey>
  	</dm:EntityOne>
  	<dm:EntityTwo>
  		<dm:EntityID>Medical_Report_4</dm:EntityID>
  		<dm:EntityCardinality>ONE</dm:EntityCardinality>
  		<dm:isEntityKey>true</dm:isEntityKey>
  	</dm:EntityTwo>
  </dm:Relation>
  <dm:Relation>
  	<dm:EntityOne>
  		<dm:EntityID>Episode_1</dm:EntityID>
  		<dm:EntityCardinality>ONE</dm:EntityCardinality>
  		<dm:isEntityKey>false</dm:isEntityKey>
  	</dm:EntityOne>
  	<dm:EntityTwo>
  		<dm:EntityID>Prescription_3</dm:EntityID>
  		<dm:EntityCardinality>MANY</dm:EntityCardinality>
  		<dm:isEntityKey>false</dm:isEntityKey>
  	</dm:EntityTwo>
  </dm:Relation>
</dm:DataModel>
